version: "3"
services:
  orderdb:
    container_name: orderdb
    image: mysql
    restart: on-failure
    ports:
      - "5009:8089"
    environment:
      - MYSQL_USER=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=@Dmin123
      - MYSQL_DATABASE=orders
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
  ordermicroservice:
    container_name: order_ms
    image: gorgeous_sandwich:order.0.0.1-SNAPSHOT
    volumes:
      - ./docker/order/:/home/app
    ports:
      - "5010:8089"
    depends_on:
      - orderdb
    environment:
      - spring.datasource.url=jdbc:mysql://orderdb:8089/orders?autoreconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=admin
      - spring.datasource.password=@Dmin123
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - logging.level.org.springframework.web=INFO