// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SandwichGQL.Data;

#nullable disable

namespace SandwichGQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221220203850_AddSandwichToDB")]
    partial class AddSandwichToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SandwichGQL.Models.Sandwich", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("Sandwiches");
                });

            modelBuilder.Entity("SandwichGQL.Models.Sandwich", b =>
                {
                    b.OwnsOne("SandwichGQL.Models.ValueObjects.Description", "description", b1 =>
                        {
                            b1.Property<int>("Sandwichid")
                                .HasColumnType("int");

                            b1.Property<string>("description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Sandwichid");

                            b1.ToTable("Sandwiches");

                            b1.WithOwner()
                                .HasForeignKey("Sandwichid");
                        });

                    b.OwnsOne("SandwichGQL.Models.ValueObjects.Designation", "designation", b1 =>
                        {
                            b1.Property<int>("Sandwichid")
                                .HasColumnType("int");

                            b1.Property<string>("designation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Sandwichid");

                            b1.ToTable("Sandwiches");

                            b1.WithOwner()
                                .HasForeignKey("Sandwichid");
                        });

                    b.OwnsOne("SandwichGQL.Models.ValueObjects.SellingPrice", "sellingPrice", b1 =>
                        {
                            b1.Property<int>("Sandwichid")
                                .HasColumnType("int");

                            b1.Property<int>("sellingPrice")
                                .HasColumnType("int");

                            b1.HasKey("Sandwichid");

                            b1.ToTable("Sandwiches");

                            b1.WithOwner()
                                .HasForeignKey("Sandwichid");
                        });

                    b.Navigation("description")
                        .IsRequired();

                    b.Navigation("designation")
                        .IsRequired();

                    b.Navigation("sellingPrice")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
